name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./CanonicalDrafter

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install elan
        run: |
          set -euxo pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          
      - name: Build project
        run: lake build
      
      - name: debug
        run: ls -R .

      - name: Run tests
        run: lake exe test
