name: Run Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build with Lean
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory: CanonicalDrafter
          build: true
          
      - name: Make test script executable
        working-directory: ./CanonicalDrafter
        run: chmod +x test.sh
        
      - name: Run tests
        working-directory: ./CanonicalDrafter
        run: |
          set -e  # Exit immediately if any command fails
          ./test.sh
          echo "Tests completed with exit code: $?"
        
      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            CanonicalDrafter/Test/*.produced.json
            CanonicalDrafter/.lake/build/ir/Test/*.ast.json
          retention-days: 7