name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    run:
      working-directory: CanonicalDrafter

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1